---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-svc
  namespace: codeserver-ns
  labels:
    name: codeserver-svc
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-deploy
spec:
  replicas: 
  selector:
    matchLabels:
      app: codeserver
      name: codeserver-po
  template:
    metadata:
      name: codeserver-po
      labels:
        app: codeserver
        name: codeserver-po
    spec:
      volumes:
      - name: codeserver-volume
        persistentVolumeClaim:
          claimName: codeserver-svc
      containers:
      - name: codeserver-container
        image: lscr.io/linuxserver/code-server:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: codeserver-cm
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /config/workspace
          name: codeserver-volume
        
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver-ns
  labels:
    app: codeserver
    name: codeserver-svc
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: codeserver-po
  ports:
  - port: 8443
    targetPort: 8443


---