---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: ws2
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
    metadata: 
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: ws2
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: NodePort
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - port: 3000
    targetPort: 3000
