---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: ws2
  labels:
    app: bggdb
    namespace: ws2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      name: bggdb-po
  template:
    metadata: 
      name: bggdb-po
      labels:
        app: bggdb
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: ws2
  labels:
    app: bggdb
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bggdb
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306