---
apiVersion: v1
kind: Namespace
metadata:
  name: ws2
  labels:
    app: bgg

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: ws2
  labels:
    app: bgg
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.ws2.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: ws2
  labels:
    app: bgg
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=